kind: pipeline
type: docker
name: dirama-devops-pipeline

steps:
  lint_and_test:
    image: python:3.12-slim
    pull: true
    commands:
      - pip install uv
      - uv sync --dev
      - pytest -q
    when:
      event:
        - push
        - pull_request

  fetch_secrets_from_vault:
    image: hashicorp/vault:1.17
    environment:
      VAULT_ADDR:
        from_secret: vault_addr
      VAULT_TOKEN:
        from_secret: vault_token
    volumes:
      - name: ci-secrets
        path: /secrets
    commands:
      - vault kv get -field=AWS_ACCESS_KEY_ID  secret/ci/project > /secrets/aws_access_key_id
      - vault kv get -field=AWS_SECRET_ACCESS_KEY secret/ci/project > /secrets/aws_secret_access_key
    when:
      event:
        - push
        - pull_request

  build_and_push_image:
    image: docker:27-cli
    pull: true
    environment:
      REGISTRY_URL:
        from_secret: registry_url
      REGISTRY_USERNAME:
        from_secret: registry_username
      REGISTRY_PASSWORD:
        from_secret: registry_password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - name: ci-secrets
        path: /secrets
    commands:
      - echo "${REGISTRY_PASSWORD}" | docker login "${REGISTRY_URL}" -u "${REGISTRY_USERNAME}" --password-stdin
      - export IMAGE_TAG="${CI_COMMIT_SHA:-latest}"
      - docker build -t "${REGISTRY_URL}/myapp:${IMAGE_TAG}" .
      - docker push "${REGISTRY_URL}/myapp:${IMAGE_TAG}"
    depends_on:
      - lint_and_test
      - fetch_secrets_from_vault

  terraform_plan:
    image: hashicorp/terraform:1.9
    pull: true
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    commands:
      - cd infra/terraform
      - terraform init -input=false
      - terraform plan -input=false -out=tfplan
    when:
      event:
        - push

  terraform_apply:
    image: hashicorp/terraform:1.9
    pull: true
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    commands:
      - cd infra/terraform
      - terraform init -input=false
      - terraform apply -input=false -auto-approve
    when:
      event:
        - tag
    depends_on:
      - terraform_plan

  helm_deploy:
    image: alpine/helm:3.15.3
    pull: true
    environment:
      KUBECONFIG:
        from_secret: kubeconfig
    commands:
      - cd infra/helm
      - export IMAGE_TAG="${CI_COMMIT_SHA:-latest}"
      - helm upgrade --install myapp ./chart \
          --set image.repository="${REGISTRY_URL}/myapp" \
          --set image.tag="${IMAGE_TAG}"
    depends_on:
      - build_and_push_image
    when:
      event:
        - tag

volumes:
  - name: ci-secrets
    temp: {}
